# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shadow < Formula
  desc "AI agent memory layer — capture corrections, create persistent rules across all your coding tools"
  homepage "https://github.com/joevilcai666/shadow"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joevilcai666/shadow/releases/download/v0.4.0/shadow_0.4.0_darwin_x86_64.tar.gz"
      sha256 "1f4e8ab6447867b935d00126380b4c174f50f6873e1fe2913b8dd61cfcf43926"

      define_method(:install) do
        bin.install "shadow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joevilcai666/shadow/releases/download/v0.4.0/shadow_0.4.0_darwin_arm64.tar.gz"
      sha256 "df2c41e058d3c63697621d29d9446cbc4812ead5c31ae8e9012098fdae9aa95e"

      define_method(:install) do
        bin.install "shadow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joevilcai666/shadow/releases/download/v0.4.0/shadow_0.4.0_linux_x86_64.tar.gz"
      sha256 "084ddd273490436a20a9d1f777374b0f37f1e30bfbe1f8403732c66c38be3aa1"
      define_method(:install) do
        bin.install "shadow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joevilcai666/shadow/releases/download/v0.4.0/shadow_0.4.0_linux_arm64.tar.gz"
      sha256 "bc0b308851f4177fa3c924c7075dbb2490d8181ccffb36f1b0275352ae02aa35"
      define_method(:install) do
        bin.install "shadow"
      end
    end
  end

  test do
    system "#{bin}/shadow version"
  end
end
